config: update validation configs
- update pre-push and pre-commit scripts, now uses package.json scripts
- echo script label for each iteration
- minor refactor

diff --git a/configs/scripts/build-packages b/configs/scripts/build-packages
--- a/configs/scripts/build-packages
+++ b/configs/scripts/build-packages
@@ -1,12 +1,16 @@
 #!/bin/bash
 
-echo "Run build packages"
-
 export CUR=$(pwd)
 
 for PACKAGE in $(ls ./packages)
 do
   cd $CUR/packages/$PACKAGE
 
-  yarn build
+  echo "Run build packages for: $PACKAGE"
+
+  if ! yarn build
+  then
+      echo "Failed to build: $PACKAGE"
+      exit 1
+  fi
 done
diff --git a/configs/scripts/check-lint b/configs/scripts/check-lint
--- a/configs/scripts/check-lint
+++ b/configs/scripts/check-lint
@@ -1,12 +1,16 @@
 #!/bin/bash
 
-echo "Run check lint"
-
 export CUR=$(pwd)
 
 for PACKAGE in $(ls ./packages)
 do
   cd $CUR/packages/$PACKAGE
 
-  yarn check-lint
+  echo "Run check lint for: $PACKAGE"
+
+  if ! yarn check-lint
+  then
+      echo "Failed to lint: $PACKAGE"
+      exit 1
+  fi
 done
diff --git a/configs/scripts/check-test b/configs/scripts/check-test
--- a/configs/scripts/check-test
+++ b/configs/scripts/check-test
@@ -1,12 +1,16 @@
 #!/bin/bash
 
-echo "Run check test"
-
 export CUR=$(pwd)
 
 for PACKAGE in $(ls ./packages)
 do
   cd $CUR/packages/$PACKAGE
 
-  yarn check-test
+  echo "Run check test for: $PACKAGE"
+
+  if ! yarn check-test
+  then
+      echo "Failed to check test for: $PACKAGE"
+      exit 1
+  fi
 done
diff --git a/configs/scripts/check-types b/configs/scripts/check-types
--- a/configs/scripts/check-types
+++ b/configs/scripts/check-types
@@ -1,12 +1,16 @@
 #!/bin/bash
 
-echo "Run check types"
-
 export CUR=$(pwd)
 
 for PACKAGE in $(ls ./packages)
 do
   cd $CUR/packages/$PACKAGE
 
-  yarn check-types
+  echo "Run check types for: $PACKAGE"
+
+  if ! yarn check-types
+  then
+      echo "Failed to check types for: $PACKAGE"
+      exit 1
+  fi
 done
diff --git a/configs/scripts/install-packages b/configs/scripts/install-packages
--- a/configs/scripts/install-packages
+++ b/configs/scripts/install-packages
@@ -1,12 +1,16 @@
 #!/bin/bash
 
-echo "Run yarn install for packages"
-
 export CUR=$(pwd)
 
 for PACKAGE in $(ls ./packages)
 do
   cd $CUR/packages/$PACKAGE
 
-  yarn
+  echo "Run yarn install for packages: $PACKAGE"
+
+  if ! yarn install --silent
+  then
+      echo "Failed to install packages for: $PACKAGE"
+      exit 1
+  fi
 done
